[package]
name = "rcore-thread"
version = "0.1.0"
authors = ["WangRunji <wangrunji0408@163.com>"]
description = "Bare-metal thread scheduler and executor"
edition = "2018"

[dependencies]
log = "0.4"
spin = "0.5"
deque = { git = "https://github.com/wangrunji0408/deque.git", branch = "no_std" }